MiaClient/MiaClient.csproj, MiaClient/frmGebruikerBeheer.Designer.cs, MiaClient/frmGebruikerBeheer.cs, MiaClient/frmGebruikerBeheer.resx
=> 25 olivier p

MiaClient/FrmGebruiksLog.cs, MiaClient/Program.cs, MiaClient/frmParameter.cs, MiaClient/mdiMia.Designer.cs, MiaClient/mdiMia.cs, MiaClient/mdiMia.resx, MiaLogic/Manager/GebruikerManager.cs, MiaLogic/Manager/RolManager.cs, MiaLogic/Object/Gebruiker.cs, MiaLogic/Object/Rol.cs
Gebruiker authenticatie
Rol authenticatie
Logs voor niet actieve gebruikers
Logs voor het aanmaken van nieuwe gebruikers
=> Tim 24 sprint 1 deel 2

MiaClient.sln, ProofOfConceptDesign/Manager/AanvraagManager.cs, ProofOfConceptDesign/Manager/GebruikerManager.cs, ProofOfConceptDesign/Manager/GebruiksLogManager.cs, ProofOfConceptDesign/Manager/ParameterManager.cs, ProofOfConceptDesign/Manager/RolManager.cs, ProofOfConceptDesign/StyleParameters.cs
Proof of concept design parameters klaar voor gebruik Parent form al wat ge designed.
=> Proof of concept design

MiaClient/FrmAanvragen.Designer.cs, MiaClient/FrmAanvragen.cs, MiaClient/UserControls/AanvraagItem.Designer.cs, MiaClient/UserControls/AanvraagItem.cs, MiaClient/frmAanvraagFormulier.cs, MiaLogic/Manager/AankoperManager.cs, MiaLogic/Manager/AanvraagManager.cs
=> Ellen sprint3 5

MiaClient/FrmAanvragen.cs, MiaClient/UserControls/AanvraagItem.Designer.cs, MiaClient/UserControls/AanvraagItem.cs, MiaClient/frmAanvraagFormulier.cs
User Story 1 Taak 6 Klaar
User Story 27 Bugs Klaar
=> Ellen sprint3 6

MiaClient/UserControls/AanvraagItem.cs, MiaClient/UserControls/FotoItem.Designer.cs, MiaClient/UserControls/FotoItem.cs, MiaClient/UserControls/OffertesItem.cs, MiaClient/frmAanvraagFormulier.Designer.cs, MiaClient/frmAanvraagFormulier.cs, MiaLogic/Manager/FotoManager.cs
User Story 29 Taak 8 klaar en fout er uitgehaald
Taak 13 bijna klaar
=> Ellen sprint4 2

MiaClient/MiaClient.csproj, MiaClient/UserControls/AanvraagItem.cs, MiaClient/UserControls/LinkItem.Designer.cs, MiaClient/UserControls/LinkItem.cs, MiaClient/UserControls/LinkItem.resx, MiaClient/frmAanvraagFormulier.cs
User Story 29 Taak 8 klaar Taak 13 bijna klaar
=> Ellen sprint4 3

MiaClient/UserControls/AanvraagItem.cs, MiaClient/UserControls/FotoItem.cs, MiaClient/UserControls/LinkItem.cs, MiaClient/frmAanvraagFormulier.Designer.cs, MiaClient/frmAanvraagFormulier.cs
=> Ellen sprint4 5

MiaClient/UserControls/LinkItem.Designer.cs, MiaClient/frmAanvraagFormulier.cs
=> Ellen sprint4 6

MiaClient/FrmAanvragen.Designer.cs, MiaClient/FrmAanvragen.cs, MiaClient/FrmAanvragen.resx, MiaClient/UserControls/AanvraagItem.Designer.cs, MiaClient/UserControls/AanvraagItem.cs, MiaClient/UserControls/LinkItem.Designer.cs, MiaClient/UserControls/LinkItem.cs, MiaClient/frmAanvraagFormulier.cs
Bugs
Horizontale scroll bar linken
bedrag geen cijfers ingeven
bedrag grote bedragen testen
Foute boodschap gebruikslog bij bewaren of verwijderen aanvraag
=> Ellen sprint5 1

MiaClient/FrmAanvragen.Designer.cs, MiaClient/FrmAanvragen.cs
Numerieke waarden bij filters op lijst aanvragen
=> Numerieke waarden bij filters op lijst aanvragen

MiaClient/UserControls/LinkItem.cs, MiaClient/UserControls/OffertesItem.cs, MiaClient/frmAanvraagFormulier.cs
leeg maken textvakken offerte foto en linken bij verwijderen
=> Ellen sprint5 6

MiaClient/App.config, MiaClient/Program.cs, MiaClient/UserControls/FotoItem.cs, MiaClient/UserControls/LinkItem.cs, MiaClient/UserControls/OffertesItem.cs, MiaClient/frmAanvraagFormulier.cs, MiaLogic/Manager/GebruikerManager.cs
=> Tim sprint 5 1

MiaClient/App.config, MiaClient/UserControls/AanvraagItem.cs
bug aanvragen die goedgekeurd zijn verwijderen
=> Ellen test

MiaClient/frmAanvraagFormulier.Designer.cs, MiaClient/mdiMia.Designer.cs, MiaClient/mdiMia.cs
=> Startcommentaar toegevoegd aan hoofdformulier en andere

MiaClient/App.config, MiaClient/FrmAanvragen.Designer.cs, MiaClient/MiaClient.csproj, MiaClient/frmAanvraagFormulier.Designer.cs, MiaClient/frmAanvraagFormulier.cs, MiaLogic/Manager/AanvraagManager.cs, MiaLogic/Object/Aanvraag.cs
Bugs 141 en 142 gefixt 
User story 17 klaar (taak 7)
=> Stage dag_1 (eerste helft)

MiaClient/frmAanvraagFormulier.Designer.cs, MiaClient/frmAanvraagFormulier.cs, MiaLogic/Manager/AanvraagManager.cs
=> Aanpassingen aanvraag formulier

MiaClient/UserControls/GoedkeurItem.cs, MiaClient/frmGoedkeuringFormulier.Designer.cs, MiaClient/frmGoedkeuringFormulier.cs, MiaClient/frmGoedkeuringFormulier.resx
US14 is bijna klaar! taak 7-15 zijn ingebouwd
=> US14 taak 7-15

MiaClient/UserControls/GoedkeurItem.cs, MiaClient/frmAanvraagFormulier.cs, MiaClient/frmGoedkeuring.Designer.cs, MiaClient/frmGoedkeuring.cs, MiaClient/frmGoedkeuring.resx
StatusEdit button werkt nog niet ik loop ermee vast het te laten werken
=> StatusEdit button codebehind afwerken

MiaClient/UserControls/GoedkeurItem.cs, MiaClient/frmGoedkeuring.Designer.cs, MiaClient/frmGoedkeuring.cs, MiaClient/frmGoedkeuring.resx
Als er op de button geklikt wordt dan geeft het programma een error weer op de Main, maar ik heb geen idee waar de fout zou kunnen zitten. Kan iemand me hierbij helpen? Alvast Bedankt!
=> Codebehind Status-Edit button

MiaClient/UserControls/AankopenItem.Designer.cs, MiaClient/UserControls/AankopenItem.resx, MiaClient/frmAankopen.cs, MiaClient/frmGeplandeAankopen.Designer.cs, MiaClient/frmGeplandeAankopen.cs, MiaClient/frmGeweigerdeAanvragen.Designer.cs, MiaClient/frmGeweigerdeAanvragen.cs
bug 176afgemaakt en is werkende, er is al een beetje code voor bug 182.
=> bug #176 Done, gestart aan bug #182

MiaClient/UserControls/AanvraagItem.cs, MiaClient/frmAanvraagFormulier.cs
enhancement #181 is af en getest, klaar voor gebruik. Hierbij ook een vraag die vrij komt wat nu de MaxPrijs is of dat de parameter die we hebben al goed is.
=> us#181 getest en klaar om in de Master te toegevoegd te worden

MiaClient/frmBudgetSpreiding.cs, MiaClient/frmBudgetspreiding.cs
Er komt nu een pie-chart in frmBudgetspreiding(in de Excel), ik kan dit verplaatsen als het moet.
=> Lise enhancement 189

MiaClient/MiaClient.csproj, MiaClient/frmGrafiekBudgetSpreiding.Designer.cs, MiaClient/frmGrafiekBudgetSpreiding.cs
grafiek budgetspreiding - in overzichten
=> Lise enhancement 197

MiaClient/frmGrafiekStatusAanvraagPerFinancieringsjaar.Designer.cs, MiaClient/frmGrafiekStatusAanvraagPerFinancieringsjaar.cs
=> US #193 af
